name: SSH to server ubuntu and remove container and image
description: SSH to server ubuntu and remove container and image

inputs:
  ssh-private-key: 
    description: SSH private key to access
    required: true
  ssh-username: 
    description: Username for SSH connection
    required: true
    default: "root"
  ssh-host: 
    description: IPv4 address of server
    required: true
  ssh-port:
    description: Port for SSH connection
    required: true
    default: "22"

runs:
 using: composite
 steps:
  - name: SSH to server ubuntu and remove container and image
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ inputs.ssh-host }}
      username: ${{ inputs.ssh-username }}
      key: ${{ inputs.ssh-private-key }}
      port: ${{ inputs.ssh-port }}
      script: |
        cd /mangahay/back-end
        docker stop comic_mangahay_be || true
        docker rm comic_mangahay_be || true
        docker rmi miraijr/mangahay-be:main || true

        docker compose up -d

        
