export const translatorGroup: TranslatorGroup = {
  id: 0,
  name: "Tanka Team",
  description: "Nhom dich",
  thumbnail:
    "https://static.vecteezy.com/system/resources/thumbnails/041/050/024/small_2x/ai-generated-purple-grunge-texture-background-and-glowing-neon-frame-generative-ai-photo.jpg",
  avatar:
    "https://play-lh.googleusercontent.com/jA5PwYqtmoFS7StajBe2EawN4C8WDdltO68JcsrvYKSuhjcTap5QMETkloXSq5soqRBqFjuTAhh28AYrA6A=w240-h480-rw",
  members: [
    {
      id: 1,
      email: "abc.@gmail.com",
      fullname: "Leader group",
      avatar: "",
      role: "manager",
    },
    {
      id: 2,
      email: "abc1.@gmail.com",
      fullname: "member group",
      avatar: "",
      role: "member",
    },
    {
      id: 3,
      email: "abc2.@gmail.com",
      fullname: "sub_manager group",
      avatar: "",
      role: "sub_manager",
    },
  ],
};

export const comics: Comic[] = [
  {
    id: 68,
    slug: "einen-koyou-wa-kanou-deshou-ka-67a00b16",
    name: "Einen Koyou wa Kanou deshou ka",
    anotherName: "Cuộc sống khi làm maid của pháp sư hướng nội",
    genres: ["manga", "yuri", "tragedy", "shounen", "action"],
    authors: ["Tanka"],
    state: "Đang tiến hành",
    thumb: "http://127.0.0.1:4566/mangahay/comics/68/1736493029845.jpeg",
    briefDescription: "<p>Cuộc sống khi làm maid của pháp sư hướng nội</p>",
    view: 15,
    star: 0,
    creatorId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    translators: ["Tanka"],
    like: 0,
    follow: 0,
    creator: {
      id: 0,
      email: "",
      fullname: "",
      avatar: "",
    },
    chapters: [],
    comments: [],
    privileges: [],
  },
  {
    id: 68,
    slug: "einen-koyou-wa-kanou-deshou-ka-67a00b16",
    name: "Einen Koyou wa Kanou deshou ka",
    anotherName: "Cuộc sống khi làm maid của pháp sư hướng nội",
    genres: ["manga", "yuri", "tragedy", "shounen", "action"],
    authors: ["Tanka"],
    state: "Đang tiến hành",
    thumb: "http://127.0.0.1:4566/mangahay/comics/68/1736493029845.jpeg",
    briefDescription: "<p>Cuộc sống khi làm maid của pháp sư hướng nội</p>",
    view: 15,
    star: 0,
    creatorId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    translators: ["Tanka"],
    like: 0,
    follow: 0,
    creator: {
      id: 0,
      email: "",
      fullname: "",
      avatar: "",
    },
    chapters: [],
    comments: [],
    privileges: [],
  },
  {
    id: 69,
    slug: "einen-koyou-wa-kanou-deshou-ka-67a00b16",
    name: "Einen Koyou wa Kanou deshou ka",
    anotherName: "Cuộc sống khi làm maid của pháp sư hướng nội",
    genres: ["manga", "yuri", "tragedy", "shounen", "action"],
    authors: ["Tanka"],
    state: "Đang tiến hành",
    thumb: "http://127.0.0.1:4566/mangahay/comics/68/1736493029845.jpeg",
    briefDescription: "<p>Cuộc sống khi làm maid của pháp sư hướng nội</p>",
    view: 15,
    star: 0,
    creatorId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    translators: ["Tanka"],
    like: 0,
    follow: 0,
    creator: {
      id: 0,
      email: "",
      fullname: "",
      avatar: "",
    },
    chapters: [],
    comments: [],
    privileges: [],
  },
  {
    id: 71,
    slug: "einen-koyou-wa-kanou-deshou-ka-67a00b16",
    name: "Einen Koyou wa Kanou deshou ka",
    anotherName: "Cuộc sống khi làm maid của pháp sư hướng nội",
    genres: ["manga", "yuri", "tragedy", "shounen", "action"],
    authors: ["Tanka"],
    state: "Đang tiến hành",
    thumb: "http://127.0.0.1:4566/mangahay/comics/68/1736493029845.jpeg",
    briefDescription: "<p>Cuộc sống khi làm maid của pháp sư hướng nội</p>",
    view: 15,
    star: 0,
    creatorId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    translators: ["Tanka"],
    like: 0,
    follow: 0,
    creator: {
      id: 0,
      email: "",
      fullname: "",
      avatar: "",
    },
    chapters: [],
    comments: [],
    privileges: [],
  },
  {
    id: 80,
    slug: "einen-koyou-wa-kanou-deshou-ka-67a00b16",
    name: "Einen Koyou wa Kanou deshou ka",
    anotherName: "Cuộc sống khi làm maid của pháp sư hướng nội",
    genres: ["manga", "yuri", "tragedy", "shounen", "action"],
    authors: ["Tanka"],
    state: "Đang tiến hành",
    thumb: "http://127.0.0.1:4566/mangahay/comics/68/1736493029845.jpeg",
    briefDescription: "<p>Cuộc sống khi làm maid của pháp sư hướng nội</p>",
    view: 15,
    star: 0,
    creatorId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    translators: ["Tanka"],
    like: 0,
    follow: 0,
    creator: {
      id: 0,
      email: "",
      fullname: "",
      avatar: "",
    },
    chapters: [],
    comments: [],
    privileges: [],
  },
  {
    id: 80,
    slug: "einen-koyou-wa-kanou-deshou-ka-67a00b16",
    name: "Einen Koyou wa Kanou deshou ka",
    anotherName: "Cuộc sống khi làm maid của pháp sư hướng nội",
    genres: ["manga", "yuri", "tragedy", "shounen", "action"],
    authors: ["Tanka"],
    state: "Đang tiến hành",
    thumb: "http://127.0.0.1:4566/mangahay/comics/68/1736493029845.jpeg",
    briefDescription: "<p>Cuộc sống khi làm maid của pháp sư hướng nội</p>",
    view: 15,
    star: 0,
    creatorId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    translators: ["Tanka"],
    like: 0,
    follow: 0,
    creator: {
      id: 0,
      email: "",
      fullname: "",
      avatar: "",
    },
    chapters: [],
    comments: [],
    privileges: [],
  },
  {
    id: 80,
    slug: "einen-koyou-wa-kanou-deshou-ka-67a00b16",
    name: "Einen Koyou wa Kanou deshou ka",
    anotherName: "Cuộc sống khi làm maid của pháp sư hướng nội",
    genres: ["manga", "yuri", "tragedy", "shounen", "action"],
    authors: ["Tanka"],
    state: "Đang tiến hành",
    thumb: "http://127.0.0.1:4566/mangahay/comics/68/1736493029845.jpeg",
    briefDescription: "<p>Cuộc sống khi làm maid của pháp sư hướng nội</p>",
    view: 15,
    star: 0,
    creatorId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    translators: ["Tanka"],
    like: 0,
    follow: 0,
    creator: {
      id: 0,
      email: "",
      fullname: "",
      avatar: "",
    },
    chapters: [],
    comments: [],
    privileges: [],
  },
  {
    id: 80,
    slug: "einen-koyou-wa-kanou-deshou-ka-67a00b16",
    name: "Einen Koyou wa Kanou deshou ka",
    anotherName: "Cuộc sống khi làm maid của pháp sư hướng nội",
    genres: ["manga", "yuri", "tragedy", "shounen", "action"],
    authors: ["Tanka"],
    state: "Đang tiến hành",
    thumb: "http://127.0.0.1:4566/mangahay/comics/68/1736493029845.jpeg",
    briefDescription: "<p>Cuộc sống khi làm maid của pháp sư hướng nội</p>",
    view: 15,
    star: 0,
    creatorId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    translators: ["Tanka"],
    like: 0,
    follow: 0,
    creator: {
      id: 0,
      email: "",
      fullname: "",
      avatar: "",
    },
    chapters: [],
    comments: [],
    privileges: [],
  },
];

export const posts: TranslatorGroupPost[] = [
  {
    id: "abc1",
    content:
      "Chuẩn bị nhóm sẽ thầu bộ này về làm nha  thầu bộ này về làm nha thầu bộ này về làm nha thầu bộ này về làm nha thầu bộ này về làm nha thầu bộ này về làm nha thầu bộ này về làm nha thầu bộ này về làm nha thầu bộ này về làm nha!",
    thumbnail:
      "https://i.pinimg.com/236x/98/b9/c8/98b9c89e4c5cb8dcab990e363246835d.jpg",
    updatedAt: new Date(),
  },
  {
    id: "abc2",
    content: "Chuẩn bị nhóm sẽ thầu bộ này về làm nha!",
    thumbnail:
      "https://i.pinimg.com/236x/98/b9/c8/98b9c89e4c5cb8dcab990e363246835d.jpg",
    updatedAt: new Date(),
  },
];

export const recruitPositions: TranslatorGroupRecruit[] = [
  {
    id: 1,
    position: "Dịch tiếng nhật",
    requirements: ["Trình độ N3"],
    policies: [
      "Lương 100k/10 trang",
      "Tham gia với đội ngũ dịch thuật với tay nghề cao -> dễ nâng trình",
    ],
    quantity: 2,
  },
  {
    id: 1,
    position: "Dịch tiếng anh",
    requirements: [
      "Trình độ dịch thuật tốt",
      "Đã từng tham gia dịch các truyện tiếng anh",
    ],
    policies: [
      "Lương 100k/10 trang",
      "Tham gia với đội ngũ dịch thuật với tay nghề cao -> dễ nâng trình",
    ],
    quantity: 2,
  },
];
